// angular/artists_page/src/app/components/name/name.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { TUpdateFilter } from '../../services/kartochki.service';

@Component({
  selector: 'app-name',
  templateUrl: './name.component.html',
  styleUrls: ['./name.component.scss']
})
export class NameComponent implements OnInit {

  @Input() disabled:boolean = false;
  @Input() value:string ="";
  @Input() updateFilter:TUpdateFilter | null = null;

  onChangedValue(event: Event) {
    if(event.target && this.updateFilter) {
      const input = event.target as HTMLInputElement;
      const value:string = input.value;
      this.updateFilter('q', value);
    }
  }

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container-Name {{disabled?'disabled':''}}" >
  <input
    type="text"
    class="name-input"
    value={{value}}
    placeholder="Наименование картины"
    (input)="onChangedValue($event)"
  />
</div>

// react_clean/functions/src/components/Name/Name.js
import React, { useState } from "react";
import "./Name.css.scss";

var timeId = 0;

function Name(props) {

  const onChangeInput = (e)=>{
    const result = e.target.value;
    setValue(result);
    if(timeId) {
      clearTimeout(timeId);
    }
    timeId = setTimeout(()=>{
      timeId = 0;
      e.target.blur();
      props.updateFilter('q', result);
    },500);
  }

  const [value, setValue] = useState(props.value || '');
  return (
    <div className={"container-Name" + ((props.disabled)?" disabled ":'')} >
      <input key="nameInput"
        type="text"
        className="name-input"
        value={value}
        placeholder="Наименование картины"
        onChange={ (e) =>{ (props.disabled) ? null : onChangeInput(e); } }
      />
    </div>
  );

}


export default Name;
