// angular/artists_page/src/app/components/collection-kartochek/collection-kartochek.component.ts
import { Component, OnInit } from '@angular/core';

import { TKartochka } from '../../services/kartochki.service';

import { CollectionService } from '../../services/collection.service';

@Component({
  selector: 'app-collection-kartochek',
  templateUrl: './collection-kartochek.component.html',
  styleUrls: ['./collection-kartochek.component.scss']
})
export class CollectionKartochekComponent implements OnInit {

  dataKartochkas: TKartochka[] = [];
  dataTotalCount: number = 0;

  constructor(
    private collection: CollectionService
  ) {  }

  ngOnInit(): void {
    this.collection.updateDataKartochkas.subscribe(_dataKartochkas => {
      this.dataKartochkas = this.collection.dataKartochkas();
      this.dataTotalCount = this.dataKartochkas.length;
    });

    this.dataKartochkas = this.collection.dataKartochkas();
    this.dataTotalCount = this.dataKartochkas.length;
  }

}

<div class="container-CollectionKartochek" >

  <div class="div-button_clear">
    <app-button_clean></app-button_clean>
  </div>

  <app-vitrina
    [dataTotalCount]="dataTotalCount"
    [dataKartochkas]="dataKartochkas"
    emltyText= "Ваша коллекция пустая!"
  ></app-vitrina>

</div>

// react_mobx/functions/src/components/CollectionKartochek/CollectionKartochek.js
import React, { useReducer } from "react";
import "./CollectionKartochek.css.scss";

import Vitrina from '../Vitrina/Vitrina';

import Collection from '../../store/Collection';
import Button from '../Button/ButtonClear';

import { observer } from 'mobx-react-lite';

function CollectionKartochek(props) {
  return (
    <div className="container-CollectionKartochek" >
      <div className="div-button_clear">
        <Button />
      </div>
      <Vitrina key="vitrina"
        dataTotalCount={Collection.size}
        dataKartochkas={Collection.dataKartochkas()}
        emltyText= {"Ваша коллекция пустая!"}
      />
    </div>
  );

}

export default observer(CollectionKartochek);
