// react_typescript/classes/src/components/Name/Name.tsx
import React, {Component} from "react";
import "./Name.css.scss";

import { TUpdateFilter } from '../../store/Kartochki';

type NameProps = {
  value: string;
  disabled: boolean;
  updateFilter?: TUpdateFilter;
};

type NameState = {
  value: string;
};

class Name extends Component<NameProps, NameState> {

  state:NameState = {
    value: ''
  };

  timeId: ReturnType<typeof setTimeout> | null = null;


  constructor(props:NameProps) {
    super(props);

    this.state = {
      value: this.props.value || ''
    }

    this.onChangeInput = this.onChangeInput.bind(this);
  }

  onChangeInput(e:React.ChangeEvent<HTMLInputElement>) {
    const result = e.target.value;
    this.setState({value: result});
    if(this.timeId) {
      clearTimeout(this.timeId);
    }
    this.timeId = setTimeout(()=>{
      this.timeId = null;
      e.target.blur();
      if(this.props.updateFilter) {
        this.props.updateFilter('q', result);
      }
    },500);

  }

  render() {
    return (
      <div className={"container-Name" + ((this.props.disabled)?" disabled ":'')} >
        <input key="nameInput"
          type="text"
          className="name-input"
          value={this.state.value}
          placeholder="Наименование картины"
          onChange={ (e:React.ChangeEvent<HTMLInputElement>) =>{ (this.props.disabled) ? null : this.onChangeInput(e); } }
        />
      </div>
    );
  }
}

export default Name;

// angular/artists_page/src/app/components/name/name.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { TUpdateFilter } from '../../services/kartochki.service';

@Component({
  selector: 'app-name',
  templateUrl: './name.component.html',
  styleUrls: ['./name.component.scss']
})
export class NameComponent implements OnInit {

  @Input() disabled:boolean = false;
  @Input() value:string ="";
  @Input() updateFilter:TUpdateFilter | null = null;

  onChangedValue(event: Event) {
    if(event.target && this.updateFilter) {
      const input = event.target as HTMLInputElement;
      const value:string = input.value;
      this.updateFilter('q', value);
    }
  }

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container-Name {{disabled?'disabled':''}}" >
  <input
    type="text"
    class="name-input"
    value={{value}}
    placeholder="Наименование картины"
    (input)="onChangedValue($event)"
  />
</div>
