// react_typescript/functions/src/components/Numeraciya/Numeraciya.tsx
import React, { useState, useEffect } from "react";
import "./Numeraciya.css.scss";

import { TUpdateFilter } from '../../store/Kartochki';

type NumeraciyaProps = {
  currentPage:number;
  minPage:number;
  maxPage:number;
  updateFilter?: TUpdateFilter;
};


type NumeraciyaSetCurrentPage = (_n:number )=>void;

const allNumeraciya:NumeraciyaSetCurrentPage[] = [];

function createNumeraciyaView(_data:{},_value:number|string) {
  return <div {..._data} >
    {_value}
  </div>
}

function Numeraciya(props:NumeraciyaProps) {
  const changeCurrentPage = (_currentPage:number)=>{
    allNumeraciya.forEach((setCurrentPage) => {
      setCurrentPage(_currentPage);
    });

    if (props.updateFilter) {
      props.updateFilter("_page", _currentPage);
    }
  }

  const [currentPage, setCurrentPage] = useState(props.currentPage || 0);
  useEffect(()=>{
    setCurrentPage(props.currentPage);
    allNumeraciya.push(setCurrentPage);
    return ()=>{
      allNumeraciya.splice(allNumeraciya.indexOf(setCurrentPage), 1);
    };
  },[props.currentPage]);

  let _current = currentPage;

  if (_current === 0 || props.minPage === 0 || props.maxPage === 0) {
    return null;
  } else {
    let _itFirst:boolean = _current === props.minPage;
    let _itLast:boolean = _current === props.maxPage

    let array_pages:number[] = [];
    for (let i = props.minPage; i <= props.maxPage; ++i) {
      array_pages.push(i)
    }

    const start_num:[string,number][] = [
      ["«",props.minPage],
      ["‹",_current-1]
    ];

    const end_num:[string,number][] = [
      ["›",_current+1],
      ["»",props.maxPage]
    ];

    return (
      <div className="container-Numeraciya">
        {start_num.map( (_arr,_index)=>{
            return createNumeraciyaView({
              key: "value_"+_arr[0] ,
              className:  "numeraciya-view " + ((_itFirst)?"is-disabled":'')  ,
              onClick: _itFirst?null:()=>changeCurrentPage(_arr[1])
            }, _arr[0]);
          })
        }

        {array_pages.map( (_value,_index)=>{
            return createNumeraciyaView({
                key: "value_"+_value ,
                className:  "numeraciya-view " + ((_value === _current)?"is-current":'') ,
                onClick: ()=>changeCurrentPage(_value)
            }, _value);
          })
        }
        {end_num.map( (_arr,_index)=>{
            return createNumeraciyaView({
              key: "value_"+_arr[0] ,
              className:  "numeraciya-view " + ((_itLast)?"is-disabled":'') ,
              onClick: _itLast?null:()=>changeCurrentPage(_arr[1])
            }, _arr[0]);
          })
        }
      </div>
    );
  }

}

export default Numeraciya;

// angular/artists_page/src/app/ui/numeraciya/numeraciya.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { TUpdateFilter } from '../../services/kartochki.service';

export type TNumeraciya = {
  currentPage:number;
  minPage:number;
  maxPage:number;
};

@Component({
  selector: 'app-numeraciya',
  templateUrl: './numeraciya.component.html',
  styleUrls: ['./numeraciya.component.scss']
})
export class NumeraciyaComponent implements OnInit {
  private _dataNumeraciya: TNumeraciya = {
    currentPage: 0,
    minPage: -1,
    maxPage: -1
  };

  private _start_num:[string,number][] = [];
  private _end_num:[string,number][] = [];

  @Input() updateFilter:TUpdateFilter | null = null;
  @Input() set dataNumeraciya(valueNumeraciya: TNumeraciya) {
    this._dataNumeraciya = valueNumeraciya;

    if (!this.is_empty()) {
      this._start_num = [
        ["«",valueNumeraciya.minPage],
        ["‹",valueNumeraciya.currentPage-1]
      ];

      this._end_num = [
        ["›",valueNumeraciya.currentPage+1],
        ["»",valueNumeraciya.maxPage]
      ];
    }
  }

  constructor() { }

  ngOnInit(): void { }

  get dataNumeraciya() {
    return this._dataNumeraciya;
  }

  get start_num(){return this._start_num;}
  get end_num(){return this._end_num;}

  counter():number[] {
    let array_pages:number[] = [];
    for (let i = this._dataNumeraciya.minPage; i <= this._dataNumeraciya.maxPage; ++i) {
      array_pages.push(i)
    }
    return array_pages;
  }

  is_empty():boolean {
    const _dNumeraciya = this.dataNumeraciya;
    return (_dNumeraciya.currentPage === 0 ||
      _dNumeraciya.minPage <= 0 &&
      _dNumeraciya.maxPage <= 0);
  }

  changeCurrentPage(_currentPage:number) {
    if (this.updateFilter) {
      this.updateFilter('_page', _currentPage);
    }
  }

}

<div class="container-Numeraciya"
  *ngIf="!is_empty()"
>

  <div
    *ngFor='let pair of start_num'
    class="numeraciya-view {{ dataNumeraciya.currentPage === dataNumeraciya.minPage?'is-disabled':'' }}"
    (click)="changeCurrentPage(pair[1])"
  >
    {{pair[0]}}
  </div>

  <div
    *ngFor='let iter of counter()'
    class="numeraciya-view {{ iter === dataNumeraciya.currentPage?'is-current':'' }}"
    (click)="changeCurrentPage(iter)"
  >
    {{iter}}
  </div>

  <div
    *ngFor='let pair of end_num'
    class="numeraciya-view {{ dataNumeraciya.currentPage === dataNumeraciya.maxPage?'is-disabled':'' }}"
    (click)="changeCurrentPage(pair[1])"
  >
    {{pair[0]}}
  </div>

</div>
