// react_mobx/functions/src/components/Numeraciya/Numeraciya.js
import React, { useState, useEffect } from "react";
import "./Numeraciya.css.scss";

import Kartochki from '../../store/Kartochki';
import { observer } from 'mobx-react-lite';


function createNumeraciyaView(_data,_value) {
  return <div {..._data} >
    {_value}
  </div>
}

function Numeraciya(props) {
  const changeCurrentPage = (_currentPage)=>{
    if (props.updateFilter) {
      props.updateFilter("_page", _currentPage);
    }
    Kartochki.setNumeraciya({currentPage: _currentPage});
  }

  const dataNumeraciya = Kartochki.dataNumeraciya;

  let _current = dataNumeraciya.currentPage;
  let _itFirst = _current === dataNumeraciya.minPage || _current == -1;
  let _itLast = _current === dataNumeraciya.maxPage || _current == -1;

  let array_pages = [];
  let from = dataNumeraciya.minPage;
  let to = dataNumeraciya.maxPage;
  if (from > 0 && to > 0) {
    for (let i = from; i <= to; ++i) {
      array_pages.push(i)
    }
  }

  if (dataNumeraciya.minPage === 0 || dataNumeraciya.maxPage === 0) {
    return null;
  } else {
    return (
      <div className="container-Numeraciya">
        {[ ["«",dataNumeraciya.minPage], ["‹",_current-1] ].map( (_arr,_index)=>{
            return createNumeraciyaView({
              key: "value_"+_arr[0] ,
              className:  "numeraciya-view " + ((_itFirst)?"is-disabled":'')  ,
              onClick: _itFirst?null:(e)=>changeCurrentPage(_arr[1], e)
            }, _arr[0]);
          })
        }

        {array_pages.map( (_value,_index)=>{
            return createNumeraciyaView({
                key: "value_"+_value ,
                className:  "numeraciya-view " + ((_value === _current)?"is-current":'') ,
                onClick: (e)=>changeCurrentPage(_value, e)
            }, _value);
          })
        }
        {[ ["›",_current+1], ["»",dataNumeraciya.maxPage] ].map( (_arr,_index)=>{
            return createNumeraciyaView({
              key: "value_"+_arr[0] ,
              className:  "numeraciya-view " + ((_itLast)?"is-disabled":'') ,
              onClick: _itLast?null:(e)=>changeCurrentPage(_arr[1], e)
            }, _arr[0]);
          })
        }
      </div>
    );
  }

}

export default observer(Numeraciya);

// angular/artists_page/src/app/ui/numeraciya/numeraciya.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { TUpdateFilter } from '../../services/kartochki.service';

export type TNumeraciya = {
  currentPage:number;
  minPage:number;
  maxPage:number;
};

@Component({
  selector: 'app-numeraciya',
  templateUrl: './numeraciya.component.html',
  styleUrls: ['./numeraciya.component.scss']
})
export class NumeraciyaComponent implements OnInit {
  private _dataNumeraciya: TNumeraciya = {
    currentPage: 0,
    minPage: -1,
    maxPage: -1
  };

  private _start_num:[string,number][] = [];
  private _end_num:[string,number][] = [];

  @Input() updateFilter:TUpdateFilter | null = null;
  @Input() set dataNumeraciya(valueNumeraciya: TNumeraciya) {
    this._dataNumeraciya = valueNumeraciya;

    if (!this.is_empty()) {
      this._start_num = [
        ["«",valueNumeraciya.minPage],
        ["‹",valueNumeraciya.currentPage-1]
      ];

      this._end_num = [
        ["›",valueNumeraciya.currentPage+1],
        ["»",valueNumeraciya.maxPage]
      ];
    }
  }

  constructor() { }

  ngOnInit(): void { }

  get dataNumeraciya() {
    return this._dataNumeraciya;
  }

  get start_num(){return this._start_num;}
  get end_num(){return this._end_num;}

  counter():number[] {
    let array_pages:number[] = [];
    for (let i = this._dataNumeraciya.minPage; i <= this._dataNumeraciya.maxPage; ++i) {
      array_pages.push(i)
    }
    return array_pages;
  }

  is_empty():boolean {
    const _dNumeraciya = this.dataNumeraciya;
    return (_dNumeraciya.currentPage === 0 ||
      _dNumeraciya.minPage <= 0 &&
      _dNumeraciya.maxPage <= 0);
  }

  changeCurrentPage(_currentPage:number) {
    if (this.updateFilter) {
      this.updateFilter('_page', _currentPage);
    }
  }

}

<div class="container-Numeraciya"
  *ngIf="!is_empty()"
>

  <div
    *ngFor='let pair of start_num'
    class="numeraciya-view {{ dataNumeraciya.currentPage === dataNumeraciya.minPage?'is-disabled':'' }}"
    (click)="changeCurrentPage(pair[1])"
  >
    {{pair[0]}}
  </div>

  <div
    *ngFor='let iter of counter()'
    class="numeraciya-view {{ iter === dataNumeraciya.currentPage?'is-current':'' }}"
    (click)="changeCurrentPage(iter)"
  >
    {{iter}}
  </div>

  <div
    *ngFor='let pair of end_num'
    class="numeraciya-view {{ dataNumeraciya.currentPage === dataNumeraciya.maxPage?'is-disabled':'' }}"
    (click)="changeCurrentPage(pair[1])"
  >
    {{pair[0]}}
  </div>

</div>
