// angular/artists_page/src/app/ui/select/select.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { TAuthor } from '../../services/authors.service';
import { TLocation } from '../../services/locations.service';
import { TUpdateFilter, TKeyFilters } from '../../services/kartochki.service';

export type TSelectItem = {
  id: number;
  idName: string;
}
export type TSelectItems = TSelectItem[];


@Component({
  selector: 'app-select',
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.scss']
})
export class SelectComponent implements OnInit {
  is_open:boolean = false;

  @Input() disabled:boolean = false;
  @Input() current:number = -1;
  @Input() variants: TSelectItems = [];
  @Input() updateFilter:TUpdateFilter | null = null;
  @Input() nameFilter: TKeyFilters | null = null;

  constructor() { }

  ngOnInit(): void {
  }

  getCurrentNameValue(curId:number):string {
    let current_value:TSelectItem = {
      id: -1,
      idName: ''
    };

    this.variants.some((item:TSelectItem) => {
      if(item !== null && item.id === curId) {
        current_value = item;
        return true;
      }
      return false;
    });

    if (current_value.id !== -1) {
      return current_value.idName;
    }
    return "Ups Ошибка";
  }

  blurFocusOut() {
    this.is_open = false
  }

  clickOnSelectButton() {
    this.is_open = !this.is_open;
  }

  clickOnSelectVariant(_current:number) {
    if(this.updateFilter && this.nameFilter !== null) {
      this.updateFilter(this.nameFilter, _current);
    }
    this.is_open = false;
  }

}

<div *ngIf="variants.length; else Loading"
  tabIndex=-1
  class="container-Select {{is_open?'opened':''}} {{disabled?'disabled':''}}"
  (blur)="blurFocusOut()"
>
  <div class="select-value text_dots">
    {{ getCurrentNameValue(current) }}
    <div
      class="select-button"
      (click)="disabled ? undefined : clickOnSelectButton()"
      (blur)="blurFocusOut()"
    >▼</div>
  </div>
    <div *ngIf="is_open"
    class="select-variants"
  >
  <div *ngFor='let item of variants'
    class="select-variant text_dots "
    (click)="clickOnSelectVariant(item.id)"
  >
    {{ item.idName}}
  </div>

  </div>

</div>

<ng-template #Loading>
  <app-loading></app-loading>
</ng-template>

// react_clean/classes/src/components/Select/Select.js
import React, {Component} from "react";
import "./Select.css.scss";

import Loading from '../Loading/Loading';

class Select extends Component {
  constructor(props) {
    super(props);

    this.state = {
      current: this.props.current || 0,
      nameValue: this.props.nameValue,
      opened: false
    }

    this.clickOnSelectButton = this.clickOnSelectButton.bind(this);
    this.clickOnSelectVariant = this.clickOnSelectVariant.bind(this);
    this.blurFocusOut = this.blurFocusOut.bind(this);
  }

  blurFocusOut() {
    this.setState({
      opened: false
    });
  }

  clickOnSelectButton() {
    this.setState({
      opened: !this.state.opened
    });
  }

  clickOnSelectVariant(_current) {
    this.props.updateFilter(this.props.nameFilter, _current);
    this.setState({
      current: _current,
      opened: false
    });
  }

  render() {
    if (this.props.values.length < 1) {
      return (
        <div className="select-container__empty" >
          <Loading />
        </div>
      );
    } else {
      const _nameValue = this.props.nameValue;
      const _open = this.state.opened && !this.props.disabled;
      let _variants = null;

      if (_open) {(
        _variants = <div className="select-variants">
        {
          this.props.values.map((_data,_index)=>{
            return <div key={"id"+_nameValue+_data.id}
              className={"select-variant text_dots "+((_data.id === this.state.current)?"current":'') }
              onClick={(e) =>  this.clickOnSelectVariant(_data.id, e) }
            >{_data[_nameValue]}</div>
          })
        }
        </div>
      )}

      return (
        <div
          tabIndex="-1"
          className={"container-Select" + ((_open)?" opened ":'') + ((this.props.disabled)?" disabled ":'') }
          onBlur={this.blurFocusOut}
        >
          <div className="select-value text_dots">
            {this.props.values.find(item => item.id === this.state.current)[_nameValue]}
            <div
              className="select-button"
              onClick={this.props.disabled ? null : this.clickOnSelectButton}
            >▼</div>
          </div>
          {_variants}
        </div>
      );
    }
  }
}

  export default Select;
