// angular/artists_page/src/app/components/name/name.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { TUpdateFilter } from '../../services/kartochki.service';

@Component({
  selector: 'app-name',
  templateUrl: './name.component.html',
  styleUrls: ['./name.component.scss']
})
export class NameComponent implements OnInit {

  @Input() disabled:boolean = false;
  @Input() value:string ="";
  @Input() updateFilter:TUpdateFilter | null = null;

  onChangedValue(event: Event) {
    if(event.target && this.updateFilter) {
      const input = event.target as HTMLInputElement;
      const value:string = input.value;
      this.updateFilter('q', value);
    }
  }

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container-Name {{disabled?'disabled':''}}" >
  <input
    type="text"
    class="name-input"
    value={{value}}
    placeholder="Наименование картины"
    (input)="onChangedValue($event)"
  />
</div>

// react_typescript/functions/src/components/Name/Name.tsx
import React, { useState } from "react";
import "./Name.css.scss";

import { TUpdateFilter } from '../../store/Kartochki';

type NameProps = {
  value: string;
  disabled: boolean;
  updateFilter?: TUpdateFilter;
};

var timeId: ReturnType<typeof setTimeout> | null = null;

function Name(props:NameProps) {

  const onChangeInput = (e:React.ChangeEvent<HTMLInputElement>)=>{
    const currentTarget = e.currentTarget;
    setValue(currentTarget.value);
    if(timeId) {
      clearTimeout(timeId);
    }
    timeId = setTimeout(()=>{
      timeId = null;
      currentTarget.blur();
      if(props.updateFilter) {
        props.updateFilter('q', currentTarget.value);
      }
    },500);
  }

  const [value, setValue] = useState<string>(props.value || '');
  return (
    <div className={"container-Name" + ((props.disabled)?" disabled ":'')} >
      <input key="nameInput"
        type="text"
        className="name-input"
        value={value}
        placeholder="Наименование картины"
        onChange={ (e: React.ChangeEvent<HTMLInputElement>)=>{ props.disabled ? null : onChangeInput(e);} }
      />
    </div>
  );

}


export default Name;
