// react_clean/classes/src/components/CollectionKartochek/CollectionKartochek.js
import React, {Component} from "react";
import "./CollectionKartochek.css.scss";

import Vitrina from '../Vitrina/Vitrina';

import Kartochki from '../../store/Kartochki';
import Authors from '../../store/Authors';
import Locations from '../../store/Locations';
import Collection from '../../store/Collection';
import Button from '../Button/ButtonClear';


import { CollectionContext } from './CollectionContext';

class CollectionKartochek extends Component {

  constructor(props) {
    super(props);
    this.state = {
      count: 0,
    };

    this.toggleView = this.toggleView.bind(this);
  }

  toggleView() {
    this.setState((state)=>({
      count: state.count + 1
    }))
  }

  render() {
    return (
      <div className="container-CollectionKartochek" >
        <CollectionContext.Provider value={ {toggleView:this.toggleView} }>
          <div className="div-button_clear">
            <Button />
          </div>
          <Vitrina key="vitrina"
              dataTotalCount={Collection.size}
              dataKartochkas={Collection.dataKartochkas()}

              emltyText= {"Ваша коллекция пустая!"}
          />
        </CollectionContext.Provider>
      </div>
    );
  }
}

export default CollectionKartochek;

// angular/artists_page/src/app/components/collection-kartochek/collection-kartochek.component.ts
import { Component, OnInit } from '@angular/core';

import { TKartochka } from '../../services/kartochki.service';

import { CollectionService } from '../../services/collection.service';

@Component({
  selector: 'app-collection-kartochek',
  templateUrl: './collection-kartochek.component.html',
  styleUrls: ['./collection-kartochek.component.scss']
})
export class CollectionKartochekComponent implements OnInit {

  dataKartochkas: TKartochka[] = [];
  dataTotalCount: number = 0;

  constructor(
    private collection: CollectionService
  ) {  }

  ngOnInit(): void {
    this.collection.updateDataKartochkas.subscribe(_dataKartochkas => {
      this.dataKartochkas = this.collection.dataKartochkas();
      this.dataTotalCount = this.dataKartochkas.length;
    });

    this.dataKartochkas = this.collection.dataKartochkas();
    this.dataTotalCount = this.dataKartochkas.length;
  }

}

<div class="container-CollectionKartochek" >

  <div class="div-button_clear">
    <app-button_clean></app-button_clean>
  </div>

  <app-vitrina
    [dataTotalCount]="dataTotalCount"
    [dataKartochkas]="dataKartochkas"
    emltyText= "Ваша коллекция пустая!"
  ></app-vitrina>

</div>
