// react_clean/functions/src/components/App/App.js
import React from "react";
import './App.css.scss';
import './listHeader.css.scss';

import {
  Switch,
  Routes,
  Route,
  NavLink,
  HashRouter as Router
} from "react-router-dom";


import CatatologKartochek from '../CatatologKartochek/CatatologKartochek';
import KartochkaView from '../KartochkaView/KartochkaView';
import CollectionKartochek from '../CollectionKartochek/CollectionKartochek';

function App(props) {
  return (
    <div className="container-App">
      <Router>
        <div className="container-header" >
          <div className="container-listHeader">
            <ul className="listHeader">
              <li key="ul_li_home">
                <NavLink to="/" >
                    <span className="normal">Католог</span>
                    <span className="bold">Католог</span>
                </NavLink>
              </li>
              <li key="ul_li_test">
                <NavLink to="/collection" >
                    <span className="normal">Коллекция</span>
                    <span className="bold">Коллекция</span>
                </NavLink>
              </li>
              <li>
                <div className="tema-sun" onClick={props.darkTema} >☀</div>
              </li>
            </ul>
          </div>
        </div>
        <Routes>
          <Route path="/" element={<CatatologKartochek />} />
          <Route path="/kartochka/:id" element={<KartochkaView />} />
          <Route path="/collection" element={<CollectionKartochek />} />
        </Routes>
      </Router>
    </div>
  );
}

export default App;

// angular/artists_page/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [
    './app.component.scss',
    './listHeader.css.scss'
  ]
})
export class AppComponent {
  title = 'artists_page';

  darkTema() {
    document.body.classList.toggle("finter-invert");
  }
}

<div class="container-App">

  <div class="container-header" >
    <div class="container-listHeader">
      <ul class="listHeader">
        <li key="ul_li_home">
          <a routerLink=""
            routerLinkActive="active"
            [routerLinkActiveOptions]="{exact:true}"
          >
            <span class="normal">Католог</span>
            <span class="bold">Католог</span>
          </a>
        </li>
        <li key="ul_li_test">
          <a routerLink="/collection" routerLinkActive="active">
            <span class="normal">Коллекция</span>
            <span class="bold">Коллекция</span>
          </a>
        </li>
        <li>
          <div class="tema-sun" (click)="darkTema()" >☀</div>
        </li>
      </ul>
    </div>
  </div>

  <div>
    <router-outlet></router-outlet>
  </div>

</div>
