// react_typescript/functions/src/components/Select/Select.tsx
import React, { useState, useEffect } from "react";
import "./Select.css.scss";

import Loading from '../Loading/Loading';
import { TUpdateFilter, TKeyFilters } from '../../store/Kartochki';
import { TAuthor } from '../../store/Authors';
import { TLocation } from '../../store/Locations';

type SelectProps = {
  disabled: boolean;
  current: number;
  nameValue: string;
  nameFilter: TKeyFilters;
  values: TAuthor[] | TLocation[];
  updateFilter?: TUpdateFilter;
};

function Select(props:SelectProps) {

  const [opened, setOpened] = useState<boolean>(false);
  const [current, setCurrent] = useState<number>(props.current || 0);

  const blurFocusOut = ()=>{
    setOpened(false);
  }

  const clickOnSelectVariant = (_current:number)=>{
    if(props.updateFilter) {
      props.updateFilter(props.nameFilter, _current);
    }
    setCurrent(_current);
    setOpened(false);
  }

  const clickOnSelectButton = ()=>{
    setOpened(!opened);
  }

  if (props.values.length < 1) {
    return (
      <div className="select-container__empty" >
        <Loading />
      </div>
    );
  } else {
    const _nameValue = props.nameValue;
    const _open = opened && !props.disabled;
    let _variants = null;

    if (_open) {(
      _variants = <div className="select-variants">
      {
        props.values.map((_data:any)=>{
          return <div key={"id"+_nameValue+_data.id}
            className={"select-variant text_dots "+((_data.id === current)?"current":'') }
            onClick={() => clickOnSelectVariant(_data.id) }
          >{_data[_nameValue]}</div>
        })
      }
      </div>
    )}

    const getCurrentNameValue = function(values:TAuthor[]|TLocation[],curId:number,_nameV:string):string {
      let current_value:TAuthor|TLocation|null = null;
      values.some((item:TAuthor|TLocation, ind:number)=>{
        if(item.id === curId) {
          current_value = item;
          return true;
        }
        return false;
      });

      if (current_value) {
        return current_value[_nameValue];
      }
      return "Ups Ошибка";
    }

    return (
      <div
        tabIndex={-1}
        className={"container-Select" + ((_open)?" opened ":'') + ((props.disabled)?" disabled ":'') }
        onBlur={blurFocusOut}
      >
        <div className="select-value text_dots">
          {getCurrentNameValue(props.values, current, _nameValue)}
          <div
            className="select-button"
            onClick={props.disabled ? undefined : clickOnSelectButton}
          >▼</div>
        </div>
        {_variants}
      </div>
    );
  }

}

  export default Select;

// angular/artists_page/src/app/ui/select/select.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { TAuthor } from '../../services/authors.service';
import { TLocation } from '../../services/locations.service';
import { TUpdateFilter, TKeyFilters } from '../../services/kartochki.service';

export type TSelectItem = {
  id: number;
  idName: string;
}
export type TSelectItems = TSelectItem[];


@Component({
  selector: 'app-select',
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.scss']
})
export class SelectComponent implements OnInit {
  is_open:boolean = false;

  @Input() disabled:boolean = false;
  @Input() current:number = -1;
  @Input() variants: TSelectItems = [];
  @Input() updateFilter:TUpdateFilter | null = null;
  @Input() nameFilter: TKeyFilters | null = null;

  constructor() { }

  ngOnInit(): void {
  }

  getCurrentNameValue(curId:number):string {
    let current_value:TSelectItem = {
      id: -1,
      idName: ''
    };

    this.variants.some((item:TSelectItem) => {
      if(item !== null && item.id === curId) {
        current_value = item;
        return true;
      }
      return false;
    });

    if (current_value.id !== -1) {
      return current_value.idName;
    }
    return "Ups Ошибка";
  }

  blurFocusOut() {
    this.is_open = false
  }

  clickOnSelectButton() {
    this.is_open = !this.is_open;
  }

  clickOnSelectVariant(_current:number) {
    if(this.updateFilter && this.nameFilter !== null) {
      this.updateFilter(this.nameFilter, _current);
    }
    this.is_open = false;
  }

}

<div *ngIf="variants.length; else Loading"
  tabIndex=-1
  class="container-Select {{is_open?'opened':''}} {{disabled?'disabled':''}}"
  (blur)="blurFocusOut()"
>
  <div class="select-value text_dots">
    {{ getCurrentNameValue(current) }}
    <div
      class="select-button"
      (click)="disabled ? undefined : clickOnSelectButton()"
      (blur)="blurFocusOut()"
    >▼</div>
  </div>
    <div *ngIf="is_open"
    class="select-variants"
  >
  <div *ngFor='let item of variants'
    class="select-variant text_dots "
    (click)="clickOnSelectVariant(item.id)"
  >
    {{ item.idName}}
  </div>

  </div>

</div>

<ng-template #Loading>
  <app-loading></app-loading>
</ng-template>
