// react_typescript/functions/src/components/Opisanie/Opisanie.tsx
import React, {Component} from "react";
import "./Opisanie.css.scss";

type OpisanieProps = {
  [key:string]:any
};

function Opisanie(props:OpisanieProps) {
  return (
    <div className="container-Opisanie">
      <div className="opisanie-data">
        <div className="opisanie-title-info">
          <div className="opisanie-title text_dots">Автор:</div>
          <div className="opisanie-info left-space text_dots" key="autor">{props.autor}</div>
        </div>

        <div className="opisanie-title-info">
          <div className="opisanie-title text_dots">Cоздано:</div>
          <div className="opisanie-info left-space text_dots" key="created">{props.created}</div>
        </div>

        <div className="opisanie-title-info">
          <div className="opisanie-title text_dots">Локация:</div>
          <div className="opisanie-info left-space text_dots"  key="location">{props.location}</div>
        </div>
      </div>
    </div>
  );
}

export default Opisanie;

// angular/artists_page/src/app/opisanie/opisanie.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { TKartochka } from '../store/Kartochki';

@Component({
  selector: 'app-opisanie',
  templateUrl: './opisanie.component.html',
  styleUrls: ['./opisanie.component.scss']
})
export class OpisanieComponent implements OnInit {

  constructor() {
}

  @Input() props: TKartochka = {
    authorId: 0,
    author: 'string',
    ​​created: 'string',
    ​​id: 0,
    ​​imageUrl: 'string',
    ​​locationId: 0,
    location: 'string',
    ​​name: 'string'
  };

  ngOnInit(): void {
  }

}

<div class="container-opisanie">
  <div class="opisanie-data">
    <div class="opisanie-title-info">
      <div class="opisanie-title text_dots">Автор:</div>
      <div class="opisanie-info left-space text_dots">
        {{ props.author }}
      </div>
    </div>

    <div class="opisanie-title-info">
      <div class="opisanie-title text_dots">Cоздано:</div>
      <div class="opisanie-info left-space text_dots" >
        {{this.props.created}}
      </div>
    </div>

    <div class="opisanie-title-info">
      <div class="opisanie-title text_dots">Локация:</div>
      <div class="opisanie-info left-space text_dots" >
        {{this.props.location}}
      </div>
    </div>
  </div>
</div>
