// angular/artists_page/src/app/vitrina/vitrina.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { TKartochka } from '../store/Kartochki';

@Component({
  selector: 'app-vitrina',
  templateUrl: './vitrina.component.html',
  styleUrls: ['./vitrina.component.scss']
})
export class VitrinaComponent implements OnInit {

  constructor() { }

  @Input() dataTotalCount: number = -1;
  @Input() dataKartochkas: TKartochka[] = [];
  @Input() emltyText: string = "Не найдено ни одной картины!";

  ngOnInit(): void {
  }

}

<div class="container-Vitrina"
  *ngIf="dataKartochkas.length; else emptyKartochkas"
>
  <app-kartocheka
    *ngFor="let itemKartochka of dataKartochkas"
    [dataKartocheka]="itemKartochka"
  ></app-kartocheka>
</div>

<ng-template #emptyKartochkas>
  <div  *ngIf="dataTotalCount < 0; then Loading else Empty"></div>
  <ng-template #Loading>
    <app-loading></app-loading>
  </ng-template>
  <ng-template #Empty>
    {{ emltyText }}
  </ng-template>
</ng-template>

// react_typescript/functions/src/components/Vitrina/Vitrina.tsx
import React, {Component} from "react";
import "./Vitrina.css";

import Kartochka from '../Kartochka/Kartochka';
import Loading from '../Loading/Loading';

import { TKartochka } from '../../store/Kartochki';
import { TAuthor } from '../../store/Authors';
import { TLocation } from '../../store/Locations';

type VitrinaProps = {
  dataTotalCount: number;
  dataKartochkas: TKartochka[];
  dataAuthors?: TAuthor[];
  dataLocations?: TLocation[];
  emltyText?: string;
};

function Vitrina(props:VitrinaProps) {
  if (props.dataKartochkas.length) {
    return (
      <div className="container-Vitrina">
      {
        props.dataKartochkas.map((dataKartochka:TKartochka)=>{
          if (!dataKartochka.autor && props.dataAuthors) {
            const _autor = props.dataAuthors.find(item => item.id === dataKartochka.authorId);
            if (_autor) {
              dataKartochka.autor = _autor["name"];
            }
          }
          if (!dataKartochka.location && props.dataLocations) {
            const _location = props.dataLocations.find(item => item.id === dataKartochka.locationId);
            if (_location) {
              dataKartochka.location = _location["location"];
            }
          }
          return <Kartochka key={"Painting"+dataKartochka.id} {...dataKartochka} />
        })
      }
      </div>
    )
  } else {
    if (props.dataTotalCount < 0) {
      return (
        <Loading />
      )
    } else {
      return (
        <div> { props.emltyText || "Не найдено ни одной картины!"} </div>
      )
    }
  }

}

export default Vitrina;
